import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { readFileSync } from "node:fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Custom plugin to embed PTY scripts as base64 at build time
const ptyEmbedPlugin = {
	name: "pty-embed",
	setup(build) {
		build.onLoad({ filter: /pty-scripts\.ts$/ }, async () => {
			const unixScript = readFileSync("scripts/terminal_pty.py", "utf8");
			const winScript = readFileSync("scripts/terminal_win.py", "utf8");
			return {
				contents: `
export const PTY_SCRIPT_B64 = "${Buffer.from(unixScript).toString("base64")}";
export const WIN_PTY_SCRIPT_B64 = "${Buffer.from(winScript).toString("base64")}";
`,
				loader: "ts",
			};
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [ptyEmbedPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
